"""first_migration

Revision ID: 4b9d9d270cf1
Revises: 
Create Date: 2023-03-12 10:59:34.897174

"""
import uuid

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b9d9d270cf1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.UUID(), nullable=False, default=uuid.uuid4()),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("tag", sa.String(length=5), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("User")
    # ### end Alembic commands ###
